### ISSUE TITLE
Does it not work on windows? 

### ISSUE THREAD

**Issue by pssolanki111** [mrgnr/camus#27]
Hi there,
Thanks for the excellent package..
I installed it on a windows machine using `pip`, and I can't seem to run it from the Command Line itself. 
`camus` is not recognized, and `python -m camus` says it can't find `camus.__main__` as the package is not directly runnable. 

So I was wondering if this package works on windows machines or not? 

I'll prolly try the package on Ubuntu later on..

Thanks :)

**Comment by mrgnr** [comment]
@pssolanki111 Unfortunately I haven't tested on Windows yet. Camus depends on the [Hypercorn](https://pypi.org/project/Hypercorn/) server (which is installed when you install Camus via pip), so as a workaround, maybe try running `hypercorn camus` instead.

**Comment by pssolanki111** [comment]
Interestingly, this seemed to work @mrgnr.. Thanks :)
